# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "pony-express"
  s.version = "0.8.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bharanee Rathna"]
  s.date = "2012-09-15"
  s.description = "A fast and lightweight mailer for ruby that uses libmimetic for generating mails"
  s.email = "deepfryed@gmail.com"
  s.extensions = ["ext/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "VERSION",
    "ext/mimetic.cxx",
    "lib/pony-express.rb",
    "lib/pony-express/test.rb",
    "mime.types"
  ]
  s.homepage = "http://github.com/deepfryed/pony-express"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "A fast and lightweight mailer"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

